services:
  kloud-health-probe:
    image: curlimages/curl:8.8.0
    container_name: kloud_health_probe
    command: >
      sh -c "while true; do
      curl -fsS http://node1:8000/status >/dev/null || echo 'health check failed';
      sleep 10;
      done"
    depends_on:
      - node1
    networks:
      - nanogrid_net
    restart: always

networks:
  nanogrid_net:
    external: true
