#!/bin/bash
# QUICK SITEMAP SUBMISSION — Google + Bing (Manual Web UI)
# Runtime: ~5 minutes

echo "═══════════════════════════════════════════════════════════════"
echo "📡 KAMELEON.LIFE — SITEMAP SUBMISSION GUIDE"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Sitemap URL: https://kameleon.life/sitemap.xml"
echo "Last Updated: 2026-05-19T07:31:55.914Z"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "STEP 1: GOOGLE SEARCH CONSOLE (5 min)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Open browser → https://search.google.com/search-console"
echo "2️⃣  Login with your Google account"
echo "3️⃣  Select property: 'kameleon.life' (or add if missing)"
echo "4️⃣  Left sidebar → Click 'Sitemaps' (under Index section)"
echo "5️⃣  Click 'Add/Test Sitemap' button"
echo "6️⃣  Paste URL: https://kameleon.life/sitemap.xml"
echo "7️⃣  Click 'SUBMIT' button"
echo "8️⃣  Wait for green checkmark ✓"
echo ""
echo "Expected: 'Sitemap successfully submitted'"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "STEP 2: BING WEBMASTER TOOLS (5 min)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Open browser → https://www.bing.com/webmasters"
echo "2️⃣  Login with your Microsoft account"
echo "3️⃣  Select site: 'kameleon.life' (or add if missing)"
echo "4️⃣  Top menu → Click 'Sitemaps'"
echo "5️⃣  Click 'Submit Sitemap' button"
echo "6️⃣  Paste URL: https://kameleon.life/sitemap.xml"
echo "7️⃣  Click 'Submit' button"
echo "8️⃣  Wait for status update"
echo ""
echo "Expected: 'Sitemap received' or 'Success'"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "MONITORING (After Submission)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Google Search Console:"
echo "  → Sitemaps tab shows submission status"
echo "  → 'Indexed pages' count updates after crawl"
echo "  → Typical delay: 2-7 days"
echo ""
echo "Bing Webmaster Tools:"
echo "  → Sitemaps tab shows status"
echo "  → Details include last download time"
echo "  → Typical delay: 24-48 hours"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✅ DONE! Submissions queued for recrawl"
echo "═══════════════════════════════════════════════════════════════"
echo ""
