[Interface]
Address = 10.10.0.1/24
PrivateKey = <HQ_PRIVATE_KEY>
ListenPort = 51820

# Compute Node
[Peer]
PublicKey = <COMPUTE_PUBLIC_KEY>
AllowedIPs = 10.10.0.2/32
Endpoint = 91.98.47.131:51820

# Failover Node
[Peer]
PublicKey = <FAILOVER_PUBLIC_KEY>
AllowedIPs = 10.10.0.3/32
Endpoint = 46.224.203.89:51820

# Helsinki Edge
[Peer]
PublicKey = <HEL_PUBLIC_KEY>
AllowedIPs = 10.10.0.4/32
Endpoint = 37.27.216.254:51820

# USA Edge
[Peer]
PublicKey = <US_PUBLIC_KEY>
AllowedIPs = 10.10.0.5/32
Endpoint = 5.161.114.189:51820

# Singapore Edge
[Peer]
PublicKey = <SG_PUBLIC_KEY>
AllowedIPs = 10.10.0.6/32
Endpoint = 5.223.75.178:51820
