name: ingestion-ci

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *'
  pull_request:
    paths:
      - '.github/workflows/ingestion.yml'
      - 'airflow/dags/**'

jobs:
  validate-dags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint DAGs
        run: |
          pipx install 'ruff==0.8.6'
          ruff check --output-format=github airflow/dags
